"""
Boston Airbnb Market Analytics Dashboard
Inside Airbnb data — Data Scientist Portfolio Project

Reads pre-processed data from ./data/ (generated by preprocess.py).
Works locally and on Render free tier.
"""

import os
import pandas as pd
import numpy as np
from dash import Dash, dcc, html, Input, Output, callback
import plotly.graph_objects as go

# ─────────────────────────────────────────────
# PALETTE & STYLE
# ─────────────────────────────────────────────
COLORS = {
    "bg":        "#F0F4F8",
    "card":      "#FFFFFF",
    "primary":   "#264653",
    "secondary": "#2A9D8F",
    "accent":    "#E9C46A",
    "alert":     "#E76F51",
    "muted":     "#A8DADC",
    "text":      "#264653",
    "subtext":   "#6C757D",
}

ROOM_COLORS = {
    "Entire home/apt": COLORS["primary"],
    "Private room":    COLORS["secondary"],
    "Hotel room":      COLORS["accent"],
    "Shared room":     COLORS["muted"],
}

CARD_STYLE = {
    "backgroundColor": COLORS["card"],
    "borderRadius": "10px",
    "padding": "20px",
    "boxShadow": "0 2px 8px rgba(0,0,0,0.07)",
}

# ─────────────────────────────────────────────
# DATA LOADING
# ─────────────────────────────────────────────
BASE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")

print("Loading pre-processed data…")
listings         = pd.read_csv(os.path.join(BASE, "listings_clean.csv"))
cal_monthly      = pd.read_csv(os.path.join(BASE, "calendar_monthly.csv"))
reviews_monthly  = pd.read_csv(os.path.join(BASE, "reviews_monthly.csv"))
reviews_per_lst  = pd.read_csv(os.path.join(BASE, "reviews_per_listing.csv"))
print("Data loaded.")

reviews_monthly["year_month"]  = pd.to_datetime(reviews_monthly["year_month"])
reviews_per_lst["year_month"]  = pd.to_datetime(reviews_per_lst["year_month"])

ALL_NEIGHBOURHOODS = sorted(listings["neighbourhood"].dropna().unique())
ALL_ROOM_TYPES     = sorted(listings["room_type"].dropna().unique())

MONTH_ORDER = ["Jan","Feb","Mar","Apr","May","Jun",
               "Jul","Aug","Sep","Oct","Nov","Dec"]

# ─────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────
def base_layout(title="", xaxis_title="", yaxis_title="", showlegend=False):
    return dict(
        title=dict(text=title,
                   font=dict(size=14, color=COLORS["text"],
                             family="Inter, Arial, sans-serif"),
                   x=0, xanchor="left"),
        paper_bgcolor=COLORS["card"],
        plot_bgcolor=COLORS["card"],
        font=dict(family="Inter, Arial, sans-serif",
                  color=COLORS["text"], size=12),
        xaxis=dict(title=xaxis_title, showgrid=False,
                   zeroline=False, tickfont=dict(size=11)),
        yaxis=dict(title=yaxis_title, showgrid=True,
                   gridcolor="#EDEDED", zeroline=False,
                   tickfont=dict(size=11)),
        showlegend=showlegend,
        margin=dict(l=10, r=10, t=40, b=10),
    )

def filter_listings(neighbourhoods, room_types):
    df = listings.copy()
    if neighbourhoods:
        df = df[df["neighbourhood"].isin(neighbourhoods)]
    if room_types:
        df = df[df["room_type"].isin(room_types)]
    return df

# ─────────────────────────────────────────────
# APP
# ─────────────────────────────────────────────
app    = Dash(__name__, title="Boston Airbnb Analytics")
server = app.server   # expose Flask server for gunicorn / Render

app.layout = html.Div(
    style={"backgroundColor": COLORS["bg"], "minHeight": "100vh",
           "fontFamily": "Inter, Arial, sans-serif", "padding": "24px 32px"},
    children=[

        # ── HEADER ───────────────────────────────────────────────────────────
        html.Div([
            html.H1("Boston Airbnb Market Analytics",
                    style={"margin": "0 0 4px 0", "color": COLORS["primary"],
                           "fontSize": "26px", "fontWeight": "700"}),
            html.P("Exploring listing supply, pricing, and seasonal demand "
                   "across Boston's 25 neighbourhoods  |  "
                   "Data: Inside Airbnb  •  Sept 2025",
                   style={"margin": 0, "color": COLORS["subtext"], "fontSize": "13px"}),
        ], style={"marginBottom": "20px"}),

        # ── GLOBAL FILTERS ───────────────────────────────────────────────────
        html.Div([
            html.Div([
                html.Label("Neighbourhood",
                           style={"fontSize": "12px", "fontWeight": "600",
                                  "color": COLORS["subtext"], "marginBottom": "4px"}),
                dcc.Dropdown(
                    id="filter-neighbourhood",
                    options=[{"label": n, "value": n} for n in ALL_NEIGHBOURHOODS],
                    value=None, placeholder="All neighbourhoods",
                    multi=True, clearable=True,
                    style={"fontSize": "13px"},
                ),
            ], style={"flex": "1", "minWidth": "220px"}),

            html.Div([
                html.Label("Room Type",
                           style={"fontSize": "12px", "fontWeight": "600",
                                  "color": COLORS["subtext"], "marginBottom": "4px"}),
                dcc.Dropdown(
                    id="filter-room-type",
                    options=[{"label": r, "value": r} for r in ALL_ROOM_TYPES],
                    value=None, placeholder="All room types",
                    multi=True, clearable=True,
                    style={"fontSize": "13px"},
                ),
            ], style={"flex": "1", "minWidth": "200px"}),

            html.P("↑ Filters apply to all charts below",
                   style={"margin": "22px 0 0 0", "fontSize": "12px",
                          "color": COLORS["subtext"], "fontStyle": "italic"}),
        ], style={"display": "flex", "gap": "16px", "alignItems": "flex-start",
                  "backgroundColor": COLORS["card"], "padding": "16px 20px",
                  "borderRadius": "10px",
                  "boxShadow": "0 2px 8px rgba(0,0,0,0.07)",
                  "marginBottom": "20px"}),

        # ── KPI ROW ───────────────────────────────────────────────────────────
        html.Div(id="kpi-row",
                 style={"display": "grid",
                        "gridTemplateColumns": "repeat(4, 1fr)",
                        "gap": "16px", "marginBottom": "20px"}),

        # ── ROW 2: Neighbourhood bar + Price box ──────────────────────────────
        html.Div([
            html.Div([
                dcc.Graph(id="chart-neighbourhood",
                          config={"displayModeBar": False},
                          style={"height": "360px"}),
                html.P("Bar length = number of listings. "
                       "Colour intensity = median nightly price. "
                       "Dorchester leads in volume; waterfront areas command premium rates.",
                       style={"fontSize": "11px", "color": COLORS["subtext"],
                              "margin": "8px 4px 0 4px"}),
            ], style={**CARD_STYLE, "flex": "3"}),

            html.Div([
                dcc.Graph(id="chart-price-dist",
                          config={"displayModeBar": False},
                          style={"height": "360px"}),
                html.P("Entire homes cost ~2× private rooms. "
                       "The line inside each box is the median; "
                       "dots above $500 are luxury outliers.",
                       style={"fontSize": "11px", "color": COLORS["subtext"],
                              "margin": "8px 4px 0 4px"}),
            ], style={**CARD_STYLE, "flex": "2"}),
        ], style={"display": "flex", "gap": "16px", "marginBottom": "20px"}),

        # ── ROW 3: Seasonal trend + Monthly availability ───────────────────────
        html.Div([
            html.Div([
                dcc.Graph(id="chart-reviews-trend",
                          config={"displayModeBar": False},
                          style={"height": "320px"}),
                html.P("Review count proxies booking activity. "
                       "Boston peaks May–Oct; winter demand drops sharply — "
                       "a strong signal for dynamic pricing strategy.",
                       style={"fontSize": "11px", "color": COLORS["subtext"],
                              "margin": "8px 4px 0 4px"}),
            ], style={**CARD_STYLE, "flex": "3"}),

            html.Div([
                dcc.Graph(id="chart-availability",
                          config={"displayModeBar": False},
                          style={"height": "320px"}),
                html.P("Orange bars = below-average availability months "
                       "(listings are tighter / more booked). "
                       "Based on forward-looking calendar data.",
                       style={"fontSize": "11px", "color": COLORS["subtext"],
                              "margin": "8px 4px 0 4px"}),
            ], style={**CARD_STYLE, "flex": "2"}),
        ], style={"display": "flex", "gap": "16px", "marginBottom": "20px"}),

        # ── ROW 4: Scatter ────────────────────────────────────────────────────
        html.Div([
            html.Div([
                dcc.Graph(id="chart-scatter",
                          config={"displayModeBar": False},
                          style={"height": "350px"}),
                html.P("Each point is a listing (sampled for performance). "
                       "The shaded zone ($80–$300) concentrates the most-reviewed listings — "
                       "the demand sweet spot for Boston.",
                       style={"fontSize": "11px", "color": COLORS["subtext"],
                              "margin": "8px 4px 0 4px"}),
            ], style={**CARD_STYLE, "flex": "1"}),
        ], style={"display": "flex", "gap": "16px", "marginBottom": "24px"}),

        # ── FOOTER ───────────────────────────────────────────────────────────
        html.P("Built with Plotly Dash  •  Data: insideairbnb.com  •  "
               "Mengyao — Data Scientist Portfolio",
               style={"textAlign": "center", "color": COLORS["subtext"],
                      "fontSize": "12px", "paddingTop": "8px"}),
    ]
)

# ─────────────────────────────────────────────
# CALLBACKS
# ─────────────────────────────────────────────

@callback(
    Output("kpi-row", "children"),
    Input("filter-neighbourhood", "value"),
    Input("filter-room-type",     "value"),
)
def update_kpis(neighbourhoods, room_types):
    df = filter_listings(neighbourhoods, room_types)

    def kpi_card(label, value, sub, highlight=False):
        return html.Div([
            html.P(label,
                   style={"margin": "0 0 4px 0", "fontSize": "11px",
                          "fontWeight": "600", "color": COLORS["subtext"],
                          "textTransform": "uppercase", "letterSpacing": "0.05em"}),
            html.P(value,
                   style={"margin": "0 0 2px 0", "fontSize": "28px",
                          "fontWeight": "700",
                          "color": COLORS["alert"] if highlight else COLORS["primary"]}),
            html.P(sub,
                   style={"margin": 0, "fontSize": "11px", "color": COLORS["subtext"]}),
        ], style={**CARD_STYLE, "textAlign": "center"})

    return [
        kpi_card("Total Listings",
                 f"{len(df):,}",
                 "active listings (prices ≤ $2K)", highlight=True),
        kpi_card("Median Nightly Price",
                 f"${df['price'].median():,.0f}",
                 "per night (USD)"),
        kpi_card("Avg Availability",
                 f"{df['availability_365'].mean():.0f} days/yr",
                 "out of 365 — higher = less booked"),
        kpi_card("Total Reviews",
                 f"{df['number_of_reviews'].sum():,}",
                 "cumulative proxy for bookings"),
    ]


@callback(
    Output("chart-neighbourhood", "figure"),
    Input("filter-neighbourhood", "value"),
    Input("filter-room-type",     "value"),
)
def update_neighbourhood(neighbourhoods, room_types):
    df = filter_listings(neighbourhoods, room_types)
    nb = (df.groupby("neighbourhood")
            .agg(count=("id", "count"), median_price=("price", "median"))
            .reset_index()
            .sort_values("count", ascending=True)
            .tail(20))

    fig = go.Figure()
    fig.add_trace(go.Bar(
        x=nb["count"], y=nb["neighbourhood"],
        orientation="h",
        marker=dict(
            color=nb["median_price"],
            colorscale=[[0, COLORS["muted"]],
                        [0.5, COLORS["secondary"]],
                        [1, COLORS["primary"]]],
            showscale=True,
            colorbar=dict(title="Median<br>Price ($)",
                          tickfont=dict(size=10), len=0.8),
        ),
        hovertemplate=(
            "<b>%{y}</b><br>"
            "Listings: %{x}<br>"
            "Median price: $%{marker.color:.0f}"
            "<extra></extra>"
        ),
    ))
    fig.update_layout(**base_layout(
        title="Listings per Neighbourhood  (colour = median nightly price)",
        xaxis_title="Number of Listings",
    ))
    return fig


@callback(
    Output("chart-price-dist", "figure"),
    Input("filter-neighbourhood", "value"),
    Input("filter-room-type",     "value"),
)
def update_price_dist(neighbourhoods, room_types):
    df = filter_listings(neighbourhoods, room_types)
    df = df[df["price"] <= 800]

    fig = go.Figure()
    for rt in ["Entire home/apt", "Private room", "Hotel room", "Shared room"]:
        subset = df[df["room_type"] == rt]["price"]
        if len(subset) == 0:
            continue
        fig.add_trace(go.Box(
            y=subset, name=rt,
            marker_color=ROOM_COLORS.get(rt, COLORS["muted"]),
            boxmean=True,
            hovertemplate=f"<b>{rt}</b><br>$%{{y:.0f}}<extra></extra>",
        ))
    fig.update_layout(**base_layout(
        title="Price Distribution by Room Type",
        yaxis_title="Nightly Price ($)",
        showlegend=False,
    ))
    fig.update_xaxes(tickangle=-20)
    return fig


@callback(
    Output("chart-reviews-trend", "figure"),
    Input("filter-neighbourhood", "value"),
    Input("filter-room-type",     "value"),
)
def update_reviews(neighbourhoods, room_types):
    df_l = filter_listings(neighbourhoods, room_types)

    # If no filter → use pre-aggregated monthly totals (fast)
    if not neighbourhoods and not room_types:
        monthly = reviews_monthly.copy()
    else:
        listing_ids = set(df_l["id"].tolist())
        monthly = (
            reviews_per_lst[reviews_per_lst["listing_id"].isin(listing_ids)]
            .groupby("year_month")["reviews"]
            .sum()
            .reset_index()
            .sort_values("year_month")
        )

    monthly = monthly[monthly["year_month"] >= "2020-01-01"]

    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=monthly["year_month"], y=monthly["reviews"],
        mode="lines",
        line=dict(color=COLORS["primary"], width=2.5),
        fill="tozeroy",
        fillcolor="rgba(38,70,83,0.08)",
        hovertemplate="%{x|%b %Y}: <b>%{y:,}</b> reviews<extra></extra>",
    ))

    if len(monthly):
        peak = monthly.loc[monthly["reviews"].idxmax()]
        fig.add_annotation(
            x=peak["year_month"], y=peak["reviews"],
            text=f"<b>Peak: {peak['reviews']:,}</b>",
            showarrow=True, arrowhead=2,
            arrowcolor=COLORS["alert"],
            font=dict(color=COLORS["alert"], size=11),
            ax=0, ay=-30,
        )

    fig.update_layout(**base_layout(
        title="Monthly Review Activity  (2020 – Present)",
        yaxis_title="Reviews / Month",
    ))
    return fig


@callback(
    Output("chart-availability", "figure"),
    Input("filter-neighbourhood", "value"),
    Input("filter-room-type",     "value"),
)
def update_availability(neighbourhoods, room_types):
    # Calendar is not filtered by room type (no room_type col in calendar).
    # If neighbourhood filter applied, use listings availability_365 as proxy.
    df_l = filter_listings(neighbourhoods, room_types)

    if not neighbourhoods and not room_types:
        avail = cal_monthly.copy()
    else:
        # Use avg availability_365 per month as a lightweight proxy
        avg_avail_pct = df_l["availability_365"].mean() / 365 * 100
        avail = cal_monthly.copy()
        # Scale the seasonal curve to the filtered subset's overall availability
        scale = avg_avail_pct / cal_monthly["pct_available"].mean()
        avail["pct_available"] = (avail["pct_available"] * scale).clip(0, 100)

    avg = avail["pct_available"].mean()

    fig = go.Figure()
    fig.add_trace(go.Bar(
        x=avail["month_name"], y=avail["pct_available"],
        marker_color=[
            COLORS["alert"] if v < avg else COLORS["secondary"]
            for v in avail["pct_available"]
        ],
        hovertemplate="%{x}: <b>%{y:.1f}%</b> available<extra></extra>",
    ))
    fig.add_hline(y=avg, line_dash="dot", line_color=COLORS["subtext"],
                  annotation_text=f"Avg {avg:.1f}%",
                  annotation_font_color=COLORS["subtext"],
                  annotation_font_size=11)
    fig.update_layout(**base_layout(
        title="Avg Nightly Availability by Month",
        yaxis_title="% Available Nights",
    ))
    fig.update_yaxes(range=[0, 100], ticksuffix="%")
    return fig


@callback(
    Output("chart-scatter", "figure"),
    Input("filter-neighbourhood", "value"),
    Input("filter-room-type",     "value"),
)
def update_scatter(neighbourhoods, room_types):
    df = filter_listings(neighbourhoods, room_types)
    df = df[df["price"] <= 800]
    df = df.sample(min(len(df), 1500), random_state=42)

    fig = go.Figure()
    for rt in ALL_ROOM_TYPES:
        sub = df[df["room_type"] == rt]
        if len(sub) == 0:
            continue
        fig.add_trace(go.Scatter(
            x=sub["price"], y=sub["number_of_reviews"],
            mode="markers", name=rt,
            marker=dict(
                color=ROOM_COLORS.get(rt, COLORS["muted"]),
                size=6, opacity=0.65,
                line=dict(width=0.5, color="white"),
            ),
            hovertemplate=(
                "<b>%{text}</b><br>"
                "Price: $%{x}<br>"
                "Reviews: %{y}<br>"
                f"Type: {rt}<extra></extra>"
            ),
            text=sub["name"].str[:40],
        ))

    fig.add_vrect(
        x0=80, x1=300,
        fillcolor=COLORS["accent"], opacity=0.08,
        annotation_text="Sweet spot ($80–$300)",
        annotation_position="top left",
        annotation_font_color=COLORS["accent"],
        annotation_font_size=11,
        line_width=0,
    )
    fig.update_layout(**base_layout(
        title="Nightly Price vs. Total Reviews  (sampled, ≤ $800)",
        xaxis_title="Nightly Price ($)",
        yaxis_title="Number of Reviews",
        showlegend=True,
    ))
    fig.update_layout(legend=dict(
        orientation="h", yanchor="bottom", y=1.02,
        xanchor="right", x=1, font=dict(size=11),
    ))
    return fig


# ─────────────────────────────────────────────
if __name__ == "__main__":
    app.run(debug=False, port=8050)
